service: shop-node-lambda-serverless
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-2

plugins:
  - serverless-webpack

custom:
    webpack:
        webpackConfig: ./webpack.config.js
        includeModules: true # enable auto-packing of external modules

functions:
  getProductsList:
    handler: src/services/productsList.getProductsList
    events:
      - httpApi:
          path: /products
          method: get
          cors: true
  getProductsById:
    handler: src/services/productsById.getProductsById
    events:
      - httpApi:
          path: /products/{productId}
          method: get
          cors: true
