service: shop-node-lambda-serverless
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-2
  environment:
    PRODUCTS_TABLE_NAME: products
    STOCKS_TABLE_NAME: stocks
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:provider.environment.PRODUCTS_TABLE_NAME}
        - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:provider.environment.STOCKS_TABLE_NAME}

plugins:
  - serverless-webpack

custom:
    webpack:
        webpackConfig: ./webpack.config.js
        includeModules: true # enable auto-packing of external modules

functions:
  getProductsList:
    handler: src/services/productsList.getProductsList
    events:
      - httpApi:
          path: /products
          method: get
          cors: true
  getProductsById:
    handler: src/services/productsById.getProductsById
    events:
      - httpApi:
          path: /products/{productId}
          method: get
          cors: true
