service: import-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-2
  environment:
    FILE_UPLOAD_BUCKET_NAME: lambda-upload-mike
    FILE_UPLOAD_BUCKET_SIGNATURE_VERSION: v4
    FILE_UPLOAD_BUCKET_PREFIX: uploaded/
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
        - s3:ListBucket
        - s3:ListBucketVersions
        - s3:GetBucketLocation
      Resource: arn:aws:s3:::${self:provider.environment.FILE_UPLOAD_BUCKET_NAME}/${self:provider.environment.FILE_UPLOAD_BUCKET_PREFIX}*
  httpApi:
    cors: true

plugins:
  - serverless-middleware
  - serverless-webpack

custom:
    webpack:
        webpackConfig: ../../webpack.config.js
        includeModules:
          packagePath: '../../package.json'
    middleware:
      pre: 
        - ../middlewares/requestInterceptor.logRequest
      pos:
        - catch: ../middlewares/responseInterceptor.errorHandler

functions:
  importProductsFile:
    handler: services/import.importProductsFile
    events:
      - httpApi:
          path: /import
          method: get
  importFileParser:
    handler: services/import.importFileParser
    events:
      - s3:
          bucket: ${self:provider.environment.FILE_UPLOAD_BUCKET_NAME}
          event: s3:ObjectCreated:*
          rules:
            - prefix: ${self:provider.environment.FILE_UPLOAD_BUCKET_PREFIX}
            - suffix: .csv
          existing: true
    middleware:
      pre: 
        - ../middlewares/requestInterceptor.logRequest