service: import-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-2
  environment:
    FILE_UPLOAD_BUCKET_NAME: lambda-upload-mike
    FILE_UPLOAD_BUCKET_SIGNATURE_VERSION: v4
    FILE_UPLOADED_PREFIX: uploaded/
    FILE_PARSED_PREFIX: parsed/
    CATALOG_ITEMS_QUEUE_URL: ${cf:shop-node-lambda-serverless-${sls:stage}.CatalogItemsQueueUrl}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
        - s3:ListBucket
        - s3:ListBucketVersions
        - s3:GetBucketLocation
        - s3:DeleteObject
      Resource:
        - arn:aws:s3:::${self:provider.environment.FILE_UPLOAD_BUCKET_NAME}/${self:provider.environment.FILE_UPLOADED_PREFIX}*
        - arn:aws:s3:::${self:provider.environment.FILE_UPLOAD_BUCKET_NAME}/${self:provider.environment.FILE_PARSED_PREFIX}*
    - Effect: Allow
      Action:
        - sqs:SendMessage
      Resource:
        - ${cf:shop-node-lambda-serverless-${sls:stage}.CatalogItemsQueueArn}
  httpApi:
    cors: true
    authorizers:
      customAuthorizer:
        type: request
        functionArn: ${cf:authorization-service-${sls:stage}.BasicAuthorizerLambdaArn}
  logs:
    restApi: true

plugins:
  - serverless-middleware
  - serverless-webpack

custom:
  webpack:
    webpackConfig: ../../webpack.config.js
    includeModules:
      packagePath: '../../package.json'
  middleware:
    pre: 
      - ../middlewares/requestInterceptor.logRequest

functions:
  importProductsFile:
    handler: services/import.importProductsFile
    events:
      - httpApi:
          path: /import
          method: get
          authorizer:
            name: customAuthorizer
    middleware:
      pos:
        - catch: ../middlewares/responseInterceptor.errorHandler
  importFileParser:
    handler: services/import.importFileParser
    events:
      - s3:
          bucket: ${self:provider.environment.FILE_UPLOAD_BUCKET_NAME}
          event: s3:ObjectCreated:*
          rules:
            - prefix: ${self:provider.environment.FILE_UPLOADED_PREFIX}
            - suffix: .csv
          existing: true
